export const ErrorCodes = {
    ERR_NOT_FOUND: "ERR_NOT_FOUND",
    ERR_VALID: "ERR_VALID",
    ERR_UNAUTHORIZED: "ERR_UNAUTHORIZED",
    ERR_CONFLICT: "ERR_CONFLICT",
    ERR_INTERNAL: "ERR_INTERNAL",
    ERR_BAD_REQUEST: "ERR_BAD_REQUEST",
    ERR_FORBIDDEN: "ERR_FORBIDDEN"
} as const;